'use client';
import './globals.css';
import Head from 'next/head';
import { useEffect } from 'react';
import {
    getAuth,
    signInWithEmailAndPassword
} from 'firebase/auth'
import { useState } from 'react';
import { useRouter } from 'next/navigation';

import { database} from './config/firebaseConfig';
export default function Register() {
    const auth = getAuth();
    const user = auth.currentUser;
   /*  const [isOpen, setIsOpen] = useState(false); */
  const router=useRouter();
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const handleLogin = () => {
        signInWithEmailAndPassword(auth, username, password)
            .then((response) => {
                console.log(response.user)
                sessionStorage.setItem('Token1', response.user.accessToken);
                sessionStorage.setItem('user.email', user.email);
                sessionStorage.setItem('user.uid', user.uid);
                console.log(user.email);
                sessionStorage.removeItem('Token2')
                router.push('/rounds/round1')
            })
            .catch((err) => {
                alert('Cannot Log in')
                console.error(err);
            })
    }
    useEffect(() => {
        let token1 = sessionStorage.getItem('Token1')
        let token2 = sessionStorage.getItem('Token2')

        if(token1){
            router.push('/rounds/round1')
        }
        if(token2){
          router.push('/')
      }
    }, [])
  return (
    <div className="mt-50 origin-top-right relative left-80 mt-24 w-[20vw] rounded-md shadow-lg bg-slate-300 ring-1 ring-black ring-opacity-5">
          <Head>
                <title>Next CRUD AUTH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
          <div
            className="py-4 px-4"
            role="menu"
            aria-orientation="vertical"
            aria-labelledby="login-menu"
            flex-col
          >
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2">
                Team Email
              </label>
              <input
                type="text"
                placeholder="Enter your Team Email"
                className="w-full px-3 py-2 border rounded-md text-black opacity-70 focus:outline-none focus:ring focus:ring-cyan-300"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2">
                Password
              </label>
              <input
                type="password"
                placeholder="Enter your Password"
                className="w-full px-3 py-2 border rounded-md text-black opacity-70 focus:outline-none focus:ring focus:ring-cyan-300"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
            <button
              onClick={handleLogin}
              className="bg-cyan-600 hover:bg-cyan-900 text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:ring focus:ring-cyan-300"
            >
              Log In
            </button>
          </div>
        </div>
    
  )
}
